# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with the official Python image that has the uv tool
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS uv

# Set the working directory in the Docker container
WORKDIR /app

# Copy only the necessary files to the container
COPY pyproject.toml uv.lock /app/

# Install the project's dependencies using the uv package manager
RUN --mount=type=cache,target=/root/.cache/uv uv sync --frozen --no-install-project --no-dev --no-editable

# Now copy all the project files
COPY . /app

# Install the project itself
RUN --mount=type=cache,target=/root/.cache/uv uv sync --frozen --no-dev --no-editable

# Final stage: production image
FROM python:3.12-slim-bookworm

# Set working directory
WORKDIR /app

# Copy installed packages from the build stage
COPY --from=uv /root/.local /root/.local
COPY --from=uv --chown=app:app /app/.venv /app/.venv

# Add Python packages to the PATH
ENV PATH="/app/.venv/bin:$PATH"

# Expose the necessary ports if any
# EXPOSE 8000 (uncomment if necessary)

# Set the default command to run the server
ENTRYPOINT ["python", "-m", "pygithub_mcp_server"]
